[tool.poetry]
authors = ["yehoshuadimarsky"]
classifiers = [
  "Topic :: Database",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: SQL",
]
description = "High-level wrapper around BCP for high performance data transfers between pandas and SQL Server. No knowledge of BCP required!!"
keywords = ["bcp", "mssql", "pandas"]
license = "MIT"
maintainers = ["Oliver Borchert <me@borchero.com>"]
name = "bcpandas"
readme = "README.md"
repository = "https://github.com/yehoshuadimarsky/bcpandas"
version = "0.0.0"

[tool.poetry.plugins."pandas.sql.engine"]
bcpandas = "bcpandas.main:to_sql"

[tool.poetry.dependencies]
pandas = ">=1.5"
pyodbc = "*"
python = ">=3.8.1"
sqlalchemy = ">=1.4"

[tool.poetry.group.dev.dependencies]
pre-commit = "*"
black = "*"
mypy = "*"
ruff = "^0"
types-setuptools = "*"

[tool.poetry.group.test.dependencies]
codetiming = "*"
docker = "*"
hypothesis = "*"
ipython = "8.10.0"
matplotlib = "*"
pytest = "*"
pytest-cov = "*"
requests = "*"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.ruff]
exclude = ["build"]
ignore = ["E501"]
line-length = 99

target-version = "py38"

[tool.ruff.lint]
select = [
  "E",
  "F",
  "W",
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
force-wrap-aliases = true

[tool.ruff.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true

[tool.mypy]
ignore_missing_imports = true
pretty = true
python_version = "3.8"
show_error_codes = true

[tool.pytest.ini_options]
addopts = "--showlocals --tb=short --strict-markers -v --cov=bcpandas --cov-report html --hypothesis-show-statistics"

[tool.coverage.run]
omit = ["bcpandas/tests/*", "benchmarks/**"]
