name: Python Package
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.x"
          enable-cache: true

      - name: Build and publish
        run: |
          poetry version ${{ github.event.release.tag_name }}  # TODO change for uv!
          uv build
          uv publish \
            --username "${{ secrets.PYPI_USERNAME }}" \
            --password "${{ secrets.PYPI_PASSWORD }}"
